"""Bounded public issue discovery; separate from trusted manual Issue intake."""
import json
import os
import re
from datetime import datetime, timezone, timedelta
from urllib.error import HTTPError
from urllib.parse import urlencode
from urllib.request import Request, build_opener

from radar.core import canonical_url, quality_gate
from radar.intake import NoRedirect
from radar.intelligence import date

QUERIES = ('manual invoice', 'manual receipt', '"copy paste" spreadsheet',
           'manual export CSV', 'repetitive workflow workaround')


def normalize_issue(issue, now):
    if not isinstance(issue, dict) or issue.get('state') != 'open' or 'pull_request' in issue:
        return None
    user = issue.get('user') or {}
    if not isinstance(user, dict) or user.get('type') != 'User':
        return None
    author = user.get('login', '')
    if not isinstance(author, str) or not author or re.search(r'bot|dependabot|renovate', author, re.I):
        return None
    created = date(issue.get('created_at'))
    if not created or not now-timedelta(days=30) <= created <= now:
        return None
    title, body = issue.get('title'), issue.get('body')
    if not isinstance(title, str) or not isinstance(body, str) or len(body) > 20000:
        return None
    url = canonical_url(issue.get('html_url', ''))
    if not re.fullmatch(r'https://github.com/[^/]+/[^/]+/issues/[0-9]+', url):
        return None
    text = title+'\n'+body
    if re.search(r'automatically generated|generated by|auto.generated|dependency update|bump version|stack trace|traceback|ci failure|build failure|hiring|job opening|full.time|hire me|we offer|our services|contact us|sponsored|referral|buy now|sign up|\b(?:i|we) (?:built|launched)\b', text, re.I):
        return None
    # Ignore template instructions, quotations and code as first-person evidence.
    evidence = re.sub(r'```[\s\S]*?```|<!--[\s\S]*?-->', '', body)
    evidence = '\n'.join(line for line in evidence.splitlines() if not line.lstrip().startswith(('>', '#')))
    if not re.search(r'invoice|receipt|spreadsheet|excel|\bcsv\b|data export|workflow', evidence, re.I):
        return None
    if not re.search(r'manual|copy.paste|workaround|repetitive|every (?:day|week)|hours|tedious|frustrat', evidence, re.I):
        return None
    # A direct first-person friction clause, not an essay/example describing others.
    direct = any(re.match(r'\s*(?:I|We|My|Our)\b', sentence, re.I)
                 and len(sentence) < 800
                 and not re.search(r'\b(?:could|would|should|example|hypothetical|research|schema|spike)\b', sentence, re.I)
                 and re.search(r'manual|copy.paste|workaround|repetitive|hours|tedious|frustrat', sentence, re.I)
                 and quality_gate({'text': sentence}, 'pain')
                 for sentence in re.split(r'(?<=[.!?])\s+|\n', evidence))
    if not direct:
        return None
    row = dict(source='github_issues', source_type='public_issue', url=url,
               author_or_company=author, title=title, text=evidence.strip(),
               published_at=created.isoformat(), evidence_text=body,
               buyer_type='Public software issue; buyer status unconfirmed')
    return row if quality_gate(row, 'pain') else None


def collect_public_issues(logger, *, opener=None, now=None, allow_anonymous=False):
    token = os.environ.get('GITHUB_TOKEN')
    if not token and not allow_anonymous:
        return [], ['GitHub public issues: SKIPPED (GITHUB_TOKEN unavailable); raw=0; eligible=0; failures=0']
    now = now or datetime.now(timezone.utc)
    opener = opener or build_opener(NoRedirect).open
    headers = {'Accept': 'application/vnd.github+json', 'User-Agent': 'OpportunityRadar/2.0',
               'X-GitHub-Api-Version': '2022-11-28'}
    if token:
        headers['Authorization'] = 'Bearer '+token
    rows, seen, stats = [], set(), []
    raw = failures = 0
    for phrase in QUERIES:
        query = f'{phrase} is:issue is:open is:public in:title,body created:>={(now-timedelta(days=30)).date()}'
        url = 'https://api.github.com/search/issues?'+urlencode(dict(q=query, per_page=8, page=1, sort='created', order='desc'))
        try:
            with opener(Request(url, headers=headers), timeout=12) as response:
                content = response.read(2_000_001)
                remaining = response.headers.get('X-RateLimit-Remaining')
            if len(content) > 2_000_000:
                raise ValueError('oversized response')
            payload = json.loads(content)
            if not isinstance(payload, dict) or not isinstance(payload.get('items'), list):
                raise ValueError('malformed response')
            items = payload['items'][:8]
            raw += len(items)
            if payload.get('incomplete_results'):
                failures += 1
                stats.append('GitHub public issues: FAILED incomplete search results')
            for item in items:
                row = normalize_issue(item, now)
                if row and row['url'] not in seen:
                    seen.add(row['url'])
                    rows.append(row)
            if remaining == '0':
                failures += 1
                stats.append('GitHub public issues: FAILED rate limit exhausted; stopped')
                break
        except Exception as exc:
            failures += 1
            logger.warning('GitHub public issue search failed: %s', type(exc).__name__)
            stats.append(f'GitHub public issues: FAILED ({type(exc).__name__})')
            if isinstance(exc, HTTPError) and exc.code in (401, 403, 429):
                break
    stats.append(f'GitHub public issues: raw={raw}; eligible={len(rows)}; failures={failures}')
    return rows, stats
